# Generated by Django 5.2 on 2025-04-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="HotelName")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="HotelLocation"),
                ),
                (
                    "pricePerNight",
                    models.CharField(max_length=20, verbose_name="pricePerNight"),
                ),
            ],
        ),
    ]
